### ISSUE TITLE
Improve transcribing process in UI

### ISSUE THREAD

**Issue by leihelondon** [bbc/digital-paper-edit-firebase#230]
**Context:**
As part of #221, @nganthi has improved the transcribing process. See design [here](https://app.zeplin.io/project/5ce554083480691e05af2f74/screen/608bd86820f3fe2fd5d4f67a) (relates to Transcripts section only).

**This ticket is to implement the following features:**
- [x] Add green tick icon next to available transcripts (check font awesome for a good match)
- [x] Show the "uploading progress bar" and offers the ability to cancel the upload. (Also remove the react-fetch-progressbar dependency as no longer in use) [cancelling moved to #248]
- [x] Show the approximate transcribing time (use media duration for now - #240 covers estimation) and offers the ability to cancel the transcribing process [cancelling moved to #248]
- [x] Show the "queued" status if the media is queued by PSTT
- [x] Show the error message if upload or transcribing fails and offers the ability to re-upload or re-transcribe [moved to #244]
- [x] Show file deleted message if media has expired (see https://github.com/bbc/digital-paper-edit-firebase/issues/195)

**Developers' notes:**
- For icons, continue using the Font Awesome library (audio, video, cancel, retry, alert icons)

**Out of scope:**
- Notify the users when their transcription is ready.
- Changing the font
