### ISSUE TITLE
Test end-to-end workflows

### ISSUE THREAD

**Issue by allishultes** [bbc/digital-paper-edit-firebase#74]
**Is your feature request related to a problem? Please describe.**

Some of the CRUD operations that we've added to Firestore have been tested with manually inputted dummy data. We need to test the end-to-end workflow of creating a new project to ensure that everything works before the data exists. 

**Describe the solution you'd like**

Please create an entirely new project to validate that the programme works without manual data entry:

- [x] Create a new project
- [x] Upload an audio file for transcription
- [ ] Ensure that the transcript view works as expected
- [x] Create a new paper edit
- [ ] Ensure the following functionality works as expected:
  - [x] Uploading a transcript with no audio works when shown in TranscriptTabContainer
  - [x] There is a dropdown list of labels with one default label in the TranscriptTabContainer
  - [x] You can create, edit and delete labels in the TranscriptTabContainer
  - [x] You can select a label option to highlight with in the TranscriptTabContainer
  - [x] You can add, edit and delete annotations in the TranscriptTabContainer (#97)
  - [x] Search functionality works in the TranscriptTabContainer (#80)
  - [x] The PaperEdit view loads before any paper-cuts have been created
  - [x] Adding new programme script elements works in the PaperEdit view
  - [ ] Adding and deleting paper-cut elements works in the PaperEdit view
  - [x] Rearranging works in the PaperEdit view
  - [ ] Every Export method works in the PaperEdit view

**Describe alternatives you've considered**

**Additional context**

**Comment by emettely** [comment]
https://github.com/bbc/digital-paper-edit-firebase/issues/80

**Comment by allishultes** [comment]
My walk-through:
 - [ ] Create a new project
 - [ ] Upload an audio file for transcription
 - [ ] Ensure that the transcript view works as expected
 - [ ] Create a new paper edit
 - [ ] Ensure the following functionality works as expected:
   - [ ] Uploading a transcript with no audio works when shown in TranscriptTabContainer
   - [ ]  There is a dropdown list of labels with one default label in the TranscriptTabContainer
    - [ ] You can create, edit and delete labels in the TranscriptTabContainer
   - [ ]  You can select a label option to highlight with in the TranscriptTabContainer
   - [ ]  You can add, edit and delete annotations in the TranscriptTabContainer
   - [ ]  Search functionality works in the TranscriptTabContainer (#80)
   - [ ]  The PaperEdit view loads before any paper-cuts have been created
    - [ ] Adding new programme script elements works in the PaperEdit view
    - [ ] Adding and deleting paper-cut elements works in the PaperEdit view
    - [ ] Rearranging works in the PaperEdit view
   - [ ]  Every Export method works in the PaperEdit view

**Comment by allishultes** [comment]
Raised #95 as part of the validation process.

When creating a new label, choosing a colour from the panel throws an error and crashes the view.

<img width="520" alt="Screenshot 2020-05-04 at 07 27 34" src="https://user-images.githubusercontent.com/22618458/80961409-eef97680-8dd8-11ea-9b9d-6662993dc277.png">

**Comment by allishultes** [comment]
Raised #97 as part of the validation process.

The transcript selections disappear when a highlight is added:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22618458/80970965-0bea7580-8dea-11ea-9d81-886d2407e8db.gif)
